server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,kafkaStreams

spring:
  application:
    name: monitoring-service
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: monitoring-service
      properties:
        processing.guarantee: at_least_once
        auto.offset.reset: earliest
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
  jackson:
    deserialization:
      fail-on-unknown-properties: false
